# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7f6046fe443060d35c531c53b54c94c45cf21b65722220c606fec3370fc84517dc117a4b6f6306d5cd2bea0e554ae2f254e6bcb9648a829df3204bd2411f51aa

test:
  secret_key_base: 86cf3ca9f6b224d12e0496af98157f0cda91135418a9b640eb0334f7899838d41c79808f8797fb8ed05928186a845d15f5c8c0ad108fd2413a0d5b2f34bcede3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
